version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "simonhollingshead"
  - package-ecosystem: "npm"
    directory: "raw/"
    schedule:
      interval: "daily"
    assignees:
      - "simonhollingshead"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "@fortawesome/fontawesome-free"
