baseURL = 'https://simonhollingshead.com/'
languageCode = 'en'
defaultcontentlanguage = 'en'
theme = 'hugo-coder'
enableEmoji = true
enableRobotsTXT = true
timeZone = 'Europe/London'
disableKinds = ['RSS']
pygmentsCodefences = true
pygmentsStyle = "solarized-dark"
title = "Simon Hollingshead"
enableGitInfo = true

[frontmatter]
	lastmod = ['lastmod', ':git']

[minify]
	minifyOutput = true

[params]
	author = 'Simon J. Hollingshead'
	footerAuthor = 'Simon Hollingshead'
	info = 'Site Reliability Engineer @ Google London'
	description = 'Personal website for Simon Hollingshead (Site Reliability Engineer at Google)'
	since = 2010
	#commit = "https://github.com/simonhollingshead/simonhollingshead.com/tree/"
	colorScheme = 'dark'
	hidecolorschemetoggle = true
	favicon_svg = "images/favicon.svg"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

[[params.social]]
	name = "Mastodon"
	icon = "fa fa-brands fa-mastodon fa-2x"
	weight = 1
	url = "https://defcon.social/@simon"
	rel = "me"

[[params.social]]
	name = "LinkedIn"
	icon = "fa fa-brands fa-linkedin-in fa-2x"
	weight = 2
	url = "https://linkedin.com/in/shollingshead"
	rel = "me"
	
[[params.social]]
	name = "Keybase"
	icon = "fa fa-brands fa-keybase fa-2x"
	weight = 3
	url = "https://keybase.io/simonh"
	rel = "me"

[[params.social]]
	name = "GitHub"
	icon = "fa fa-brands fa-github fa-2x"
	weight = 4
	url = "https://github.com/simonhollingshead"
	rel = "me"

[[params.social]]
	name = "Email"
	icon = "fa fa-envelope fa-2x"
	weight = 5
	url = "mailto:me@simonhollingshead.com"
	rel = "me"

[[menu.main]]
	name = "CV"
	weight = 1
	url = "/cv/"
