module.exports = {
    multipass: true,
    js2svg: { pretty: false },
    plugins: [
        'cleanupAttrs',
        'cleanupEnableBackground',
        'cleanupIds',
        { name: 'cleanupListOfValues', params: { floatPrecision: 0, leadingZero: false } },
        { name: 'cleanupNumericValues', params: { floatPrecision: 0, leadingZero: false } },
        'collapseGroups',
        'convertColors',
        'convertEllipseToCircle',
        'convertOneStopGradients',
        { name: 'convertPathData', params: { floatPrecision: 0, transformPrecision: 0, noSpaceAfterFlags: true } },
        { name: 'convertShapeToPath', params: { convertArcs: true, floatPrecision: 0 } },
        'convertStyleToAttrs',
        { name: 'convertTransform', params: { degPrecision: 0, floatPrecision: 0, transformPrecision: 0, leadingZero: false } },
        { name: 'mergePaths', params: { floatPrecision: 0, noSpaceAfterFlags: true } },
        'mergeStyles',
        'minifyStyles',
        'moveElemsAttrsToGroup',
        'moveGroupAttrsToElems',
        // SVGO doesn't remove vendor-specific styles, so removing "style" is actually just deleting -inkscape-font-specification.
        { name: 'removeAttrs', params: { attrs: ["font-family", "font-size", "font-stretch", "font-weight", "style"] } },
        { name: 'removeComments', params: { preservePatterns: false } },
        { name: 'removeDesc', params: { removeAny: true } },
        'removeDimensions',
        'removeDoctype',
        'removeEditorsNSData',
        'removeEmptyAttrs',
        'removeEmptyContainers',
        'removeEmptyText',
        'removeHiddenElems',
        'removeMetadata',
        'removeNonInheritableGroupAttrs',
        'removeOffCanvasPaths',
        'removeStyleElement',
        'removeTitle',
        { name: 'removeUnknownsAndDefaults', params: { keepAriaAttrs: false, keepDataAttrs: false } },
        'removeUnusedNS',
        'removeUselessDefs',
        { name: 'removeUselessStrokeAndFill',  params: { removeNone: true }},
        'removeXMLProcInst',
        'reusePaths',
        'sortAttrs',
        'sortDefsChildren',
    ],
}
