name: Hugo Autobuild

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          submodules: true
          fetch-depth: 0
      
      - name: Copy CV into place
        run: cp submodules/cv/cv.pdf static/cv.pdf

      - name: Setup Node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: '*'
          check-latest: false
          cache: 'npm'
          cache-dependency-path: raw/package-lock.json
      
      - name: Prepare apt
        run: sudo apt update

      - name: Install Packages
        working-directory: raw
        run: npm i
      
      - name: Install Imagemagick and Delegates
        run: sudo apt install imagemagick inkscape

      - name: Optimise SVG and Make Static
        working-directory: raw
        run: npx svgo favicon.svg -o ../static/images/favicon.svg

      - name: Make favicon.ico
        run: convert -background transparent -define 'icon:auto-resize=48,32,16' raw/favicon.svg static/favicon.ico

      - name: Make Other Favicon Sizes
        run: |
          inkscape -w 512 -h 512 raw/favicon.svg -o static/images/android-chrome-512x512.png
          inkscape -w 192 -h 192 raw/favicon.svg -o static/images/android-chrome-192x192.png
          inkscape -w 180 -h 180 raw/favicon.svg -o static/images/apple-touch-icon.png
          inkscape -w 48 -h 48 raw/favicon.svg -o static/images/favicon-48x48.png
          inkscape -w 32 -h 32 raw/favicon.svg -o static/images/favicon-32x32.png
          inkscape -w 16 -h 16 raw/favicon.svg -o static/images/favicon-16x16.png

      - name: Remove Unused FontAwesome Icons
        working-directory: raw
        run: |
          node fas.mjs
          cat replacement_variables.scss >> ../themes/hugo-coder/assets/scss/font-awesome/_variables.scss
          : > ../themes/hugo-coder/assets/scss/font-awesome/regular.scss
          sed -i '/fa-regular-400/d' ../themes/hugo-coder/layouts/partials/head/theme-styles.html

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d # v2.6.0
        with:
          hugo-version: '0.112.1'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: simonhollingshead.com
