name: Hugo Autobuild

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      
      - name: Copy CV into place
        run: cp submodules/cv/cv.pdf static/cv.pdf

      - run: stat raw/favicon.svg

      - name: Optimise SVG
        uses: ericcornelissen/svgo-action@v3
        with:
          svgo-config: raw/svgo.config.js
          svgo-version: 3
      
      - run: stat raw/favicon.svg

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: simonhollingshead.com
