name: Hugo Autobuild

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      
      - name: Copy CV into place
        run: cp submodules/cv/cv.pdf static/cv.pdf

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install Packages
        working-directory: raw
        run: npm i
      
      - name: Install Imagemagick and Delegates
        run: sudo apt install imagemagick inkscape

      - name: Optimise SVG and Make Static
        working-directory: raw
        run: npx svgo favicon.svg -o ../static/favicon.svg

      - name: Make favicon.ico
        run: convert -background transparent -define 'icon:auto-resize=48,32,16' raw/favicon.svg static/favicon.ico

      - name: Make Other Favicon Sizes
        run: inkscape -w 512 -h 512 raw/favicon.svg -o static/android-chrome-512x512.png && inkscape -w 192 -h 192 raw/favicon.svg -o static/android-chrome-192x192.png && inkscape -w 180 -h 180 raw/favicon.svg -o static/apple-touch-icon.png

      - name: Remove Unused FontAwesome Icons
        working-directory: raw
        run: |
          node fas.mjs
          : > ../themes/hugo-coder/assets/scss/font-awesome/regular.scss
          : > ../themes/hugo-coder/static/fonts/fa-regular-400.ttf
          : > ../themes/hugo-coder/static/fonts/fa-regular-400.woff2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: simonhollingshead.com
